# MOD00: Wed Nov 15 14:21:52 WIB 2017 by RMS46

all:
	mkdir -p mountdir
	mkdir -p rootdir
	echo "bogus file" > rootdir/bogus.txt

mostlyclean clean distclean mainainer-clean:
	rm -rf mountdir rootdir bbfs.log

# distdir:
# cp Makefile $(distdir)

