all:
	mkdir -p mountdir
	mkdir -p rootdir
	echo "bogus file" > rootdir/bogus.txt

mostlyclean clean distclean mainainer-clean:
	rm -rf mountdir rootdir
	rm -rf bbfs.log

# distdir:
#	cp Makefile $(distdir)

